In [1]:
#tensorflow 다운그레이드
!pip uninstall tensorflow

Found existing installation: tensorflow 2.8.0
Uninstalling tensorflow-2.8.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.8.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.8.0


In [2]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3 MB 24 kB/s 
     |████████████████████████████████| 3.8 MB 37.3 MB/s 
     |████████████████████████████████| 50 kB 6.2 MB/s 
     |████████████████████████████████| 503 kB 55.1 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=a5bcd23ba6b76060fabc59da332679c91b5e6776a0cb1a3ed3e4eeb1c781129b
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Succes

In [4]:
import tensorflow as tf
import numpy as np

#다변수 계산에서는 매트릭스(행렬곱)를 활용함
x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91., 98., 66.]
x3_data = [75., 93., 90., 100., 70.]
y_data = [152., 185., 180., 196., 142.]

x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

Y = tf.placeholder(tf.float32)

w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = x1*w1 + x2*w2 + x3*w3 + b


In [5]:
#나머진 똑같음
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [6]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #경사하강법 쓴거임
train = optimizer.minimize(cost)

In [7]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [11]:
for step in range(8001):
    _, cost_val, hy_val = sess.run(
        [train, cost, hypothesis], feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data}
    )
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  67794.81 
Prediction:
 [ -73.54034   -96.73923   -90.606476 -103.76809   -71.63484 ]
100 Cost:  11.962987 
Prediction:
 [157.34981 180.99748 182.93501 194.13408 140.24547]
200 Cost:  11.497812 
Prediction:
 [157.23376 181.07613 182.89835 194.11618 140.34145]
300 Cost:  11.05634 
Prediction:
 [157.12071 181.15274 182.8626  194.0989  140.43475]
400 Cost:  10.6374855 
Prediction:
 [157.01062 181.22736 182.82774 194.08223 140.52545]
500 Cost:  10.239914 
Prediction:
 [156.90335 181.3     182.79378 194.06622 140.61362]
600 Cost:  9.862513 
Prediction:
 [156.79887 181.37082 182.76064 194.05077 140.69931]
700 Cost:  9.504457 
Prediction:
 [156.6971  181.4397  182.72838 194.0359  140.7826 ]
800 Cost:  9.164389 
Prediction:
 [156.59793 181.50684 182.69688 194.02162 140.86351]
900 Cost:  8.841568 
Prediction:
 [156.50133 181.5722  182.66618 194.00787 140.94217]
1000 Cost:  8.535074 
Prediction:
 [156.40721 181.63585 182.63626 193.99467 141.0186 ]
1100 Cost:  8.243988 
Prediction:
 [156.