In [ ]:
#tensorflow 다운그레이드
!pip uninstall tensorflow

Found existing installation: tensorflow 2.8.0
Uninstalling tensorflow-2.8.0:
  Would remove:
    /usr/local/bin/estimator_ckpt_converter
    /usr/local/bin/import_pb_to_tensorboard
    /usr/local/bin/saved_model_cli
    /usr/local/bin/tensorboard
    /usr/local/bin/tf_upgrade_v2
    /usr/local/bin/tflite_convert
    /usr/local/bin/toco
    /usr/local/bin/toco_from_protos
    /usr/local/lib/python3.7/dist-packages/tensorflow-2.8.0.dist-info/*
    /usr/local/lib/python3.7/dist-packages/tensorflow/*
Proceed (y/n)? y
  Successfully uninstalled tensorflow-2.8.0


In [1]:
!pip install tensorflow==1.15

     |████████████████████████████████| 412.3 MB 21 kB/s 
     |████████████████████████████████| 50 kB 5.8 MB/s 
     |████████████████████████████████| 503 kB 64.3 MB/s 
     |████████████████████████████████| 3.8 MB 39.8 MB/s 
  Created wheel for gast: filename=gast-0.2.2-py3-none-any.whl size=7554 sha256=c0db9d25caab833b81e9fa588bb55adfcb49802d495a75de2876bea03edaaff6
  Stored in directory: /root/.cache/pip/wheels/21/7f/02/420f32a803f7d0967b48dd823da3f558c5166991bfd204eef3
Successfully built gast
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Succes

In [2]:
import tensorflow as tf
import numpy as np

#다변수 계산에서는 매트릭스(행렬곱)를 활용함
x_data = [[73., 80., 75.], [93., 88., 93.], [89., 91., 90.], [96., 98., 100.], [73., 66., 70.]]
y_data = [[152.], [185.], [180.], [196.], [142.]]

X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight1')
b = tf.Variable(tf.random_normal([1]), name='bias')

hypothesis = tf.matmul(X, W) + b

In [3]:
#나머진 똑같음
#cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [4]:
#Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5) #경사하강법 쓴거임
train = optimizer.minimize(cost)

In [5]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [7]:
for step in range(8001):
    _, cost_val, hy_val = sess.run(
        [train, cost, hypothesis], feed_dict={X: x_data, Y: y_data}
    )
    if step % 100 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  13.072301 
Prediction:
 [[155.61526]
 [181.86847]
 [181.79506]
 [199.03064]
 [136.51567]]
100 Cost:  12.424863 
Prediction:
 [[155.351  ]
 [181.79518]
 [181.59615]
 [198.82314]
 [136.51306]]
200 Cost:  11.833284 
Prediction:
 [[155.22533]
 [181.88185]
 [181.5583 ]
 [198.79063]
 [136.63112]]
300 Cost:  11.272529 
Prediction:
 [[155.10304]
 [181.9662 ]
 [181.5215 ]
 [198.7589 ]
 [136.74611]]
400 Cost:  10.741121 
Prediction:
 [[154.98412]
 [182.04826]
 [181.4857 ]
 [198.72792]
 [136.85811]]
500 Cost:  10.237553 
Prediction:
 [[154.86841]
 [182.12808]
 [181.4509 ]
 [198.69766]
 [136.96715]]
600 Cost:  9.760321 
Prediction:
 [[154.75587]
 [182.20575]
 [181.41707]
 [198.66814]
 [137.07335]]
700 Cost:  9.307963 
Prediction:
 [[154.6464 ]
 [182.28131]
 [181.38419]
 [198.63928]
 [137.17679]]
800 Cost:  8.879164 
Prediction:
 [[154.5399 ]
 [182.35484]
 [181.35219]
 [198.6111 ]
 [137.27754]]
900 Cost:  8.472746 
Prediction:
 [[154.4363 ]
 [182.42636]
 [181.3211 ]
 [198.58357]
 [137.3756